services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: database_name
    volumes:
      - weather_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - weather_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - weather_network

volumes:
  weather_data:

networks:
  weather_network:
    driver: bridge
